version: '3.8'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: tasks
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    depends_on:
      - db
    env_file: .env

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    depends_on:
      - db
    ports:
      - "8000:8000"
    env_file: .env

volumes:
  postgres_data: